Highlight code blocks, fix emphasis
WICG/webcomponents pull request #712
Opened 2017-11-20 20:06 UTC by wiinci

2017-11-20 20:07 UTC, wiinci commented
Marked as non substantive for IPR from ash-nazg.

2017-11-21 00:25 UTC, rniwa requested changes

2017-11-21 00:25 UTC, rniwa commented on proposals/Template-Instantiation.md
> +        1. Run the concept to _adjust single node case_ with *currentNode.*
`.` Should appear after *.

2017-11-21 00:25 UTC, rniwa commented on proposals/Template-Instantiation.md
> +    <h1>Ryosuke Niwa</h1>
Please don't reformat examples like this. Whitespaces after h1 Before "Email:" would not be collapsed so it would affect the final DOM tree.

2017-11-21 00:25 UTC, rniwa commented on proposals/Template-Instantiation.md
> +    <h1>Ryosuke Niwa</h1>
Ditto.

2017-11-21 00:25 UTC, rniwa commented on proposals/Template-Instantiation.md
> +    <div class="foo {{ f(y) }}">{{ x }} world</div>
Ditto.

2017-11-21 00:26 UTC, rniwa commented on proposals/Template-Instantiation.md
> +        <h1>{{name}}</h1>
Please undo this reformatting.

2017-12-04 22:09 UTC, merged

2017-12-04 22:09 UTC, rniwa commented
Thanks for the fixes!